repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the latest version of pre-commit-hooks
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit, pre-push]
      - id: check-yaml
        stages: [pre-commit, pre-push]
      - id: end-of-file-fixer
        stages: [pre-commit, pre-push]
      - id: check-added-large-files
        stages: [pre-commit, pre-push]
  - repo: https://github.com/psf/black
    rev: 22.3.0  # Use the latest version of Black
    hooks:
      - id: black
        language_version: python3
        stages: [pre-commit, pre-push]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (Python imports)
        stages: [pre-commit, pre-push]
